<?php

namespace Rgbcode_menu\classes\plugins;

use Rgbcode_menu\traits\Singleton;

class ACF {

	use Singleton;

	public function __construct() {
		//      options page
		//      https://www.advancedcustomfields.com/resources/options-page/
		add_action( 'init', [ $this, 'register_options_page' ] );

		//      in this hook you need register your fields
		//      https://www.advancedcustomfields.com/resources/register-fields-via-php/
		add_action( 'init', [ $this, 'register_fields' ] );
	}

	public function register_options_page() {

		if ( function_exists( 'acf_add_options_page' ) ) {
			acf_add_options_page(
				[
					'page_title' => __( 'Rgbcode Map', 'rgbcode-map' ),
					'menu_title' => __( 'Rgbcode Map', 'rgbcode-map' ),
					'menu_slug'  => 'rgbcode-map-options',
					'capability' => 'edit_posts',
					'icon_url'   => 'dashicons-admin-site-alt3', // Add this line and replace the second inverted commas with class of the icon you like
					'position'   => 30,
					'redirect'   => false,
				]
			);
		}
	}

	public function register_fields() {

		if ( function_exists( 'acf_add_local_field_group' ) ) {
			// Resources (for post-type Resources)

			acf_add_local_field_group(
				array(
					'key'                   => 'group_61dfd87bc5343',
					'title'                 => 'Resource',
					'fields'                => array(
						array(
							'key'               => 'field_61dfd88fdf34d',
							'label'             => 'description',
							'name'              => 'sx_description',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => '',
							'rows'              => 4,
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_621b20d6ef5bf',
							'label'             => 'Resource type',
							'name'              => 'resources_link_choice',
							'type'              => 'radio',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'direct' => 'Direct Link',
								'upload' => 'Upload file',
							),
							'allow_null'        => 0,
							'other_choice'      => 0,
							'default_value'     => '',
							'layout'            => 'horizontal',
							'return_format'     => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key'               => 'field_61dfd8d8df34e',
							'label'             => 'Document',
							'name'              => 'sx_document',
							'type'              => 'file',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_621b20d6ef5bf',
										'operator' => '==',
										'value'    => 'upload',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'url',
							'library'           => 'all',
							'min_size'          => '',
							'max_size'          => 10,
							'mime_types'        => '',
						),
						array(
							'key'               => 'field_621b21a3ef5c0',
							'label'             => 'Link',
							'name'              => 'resource_direct_link',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_621b20d6ef5bf',
										'operator' => '==',
										'value'    => 'direct',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
						),
					),
					'location'              => array(
						array(
							array(
								'param'    => 'post_type',
								'operator' => '==',
								'value'    => 'resource',
							),
						),
					),
					'menu_order'            => 0,
					'position'              => 'normal',
					'style'                 => 'default',
					'label_placement'       => 'top',
					'instruction_placement' => 'label',
					'hide_on_screen'        => '',
					'active'                => true,
					'description'           => '',
					'show_in_rest'          => 0,
				)
			);

			// Dynamic Map Settings (for template Map.php)
			acf_add_local_field_group(
				array(
					'key'                   => 'group_61e94357d20f5',
					'title'                 => 'Dynamic Map Settings',
					'fields'                => array(
						array(
							'key'               => 'field_61f7e5663ca1b',
							'label'             => 'Titles',
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_61f7e5823ca1c',
							'label'             => 'First Block',
							'name'              => 'first_block',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Statistics',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61f7e5a53ca1d',
							'label'             => 'Second Block',
							'name'              => 'second_block',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Top CVEs',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61f7e5ba3ca1e',
							'label'             => 'Third Block',
							'name'              => 'third_block',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Top Malware',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61f7e5e43ca1z',
							'label'             => 'Avg price title (arrow)',
							'name'              => 'avg_price_title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Avg. cc Price',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61f7e5e43ca1f',
							'label'             => 'Total CVEs title',
							'name'              => 'total_cves_title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Total CVEs',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61e94bdced5d2',
							'label'             => 'Tooltips',
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_61e94c17fb3c1',
							'label'             => 'Statistic tooltip',
							'name'              => 'statistic_tooltip',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_61e94cdc69d57',
									'label'             => 'Text',
									'name'              => 'text',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => '',
									'rows'              => 3,
									'new_lines'         => '',
								),
								array(
									'key'               => 'field_61e94ceb69d58',
									'label'             => 'Link',
									'name'              => 'link',
									'type'              => 'url',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
								),
							),
						),
						array(
							'key'               => 'field_61e94d38cb02f',
							'label'             => 'CVEs tooltip',
							'name'              => 'cves_tooltip',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_61e94d38cb030',
									'label'             => 'Text',
									'name'              => 'text',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => '',
									'rows'              => 3,
									'new_lines'         => '',
								),
								array(
									'key'               => 'field_61e94d38cb031',
									'label'             => 'Link',
									'name'              => 'link',
									'type'              => 'url',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
								),
							),
						),
						array(
							'key'               => 'field_61e94d57cb032',
							'label'             => 'Malware tooltip',
							'name'              => 'malware_tooltip',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_61e94d57cb033',
									'label'             => 'Text',
									'name'              => 'text',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => '',
									'rows'              => 3,
									'new_lines'         => '',
								),
								array(
									'key'               => 'field_61e94d57cb034',
									'label'             => 'Link',
									'name'              => 'link',
									'type'              => 'url',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
								),
							),
						),
					),
					'location'              => array(
						array(
							array(
								'param'    => 'page_template',
								'operator' => '==',
								'value'    => 'map.php',
							),
						),
					),
					'menu_order'            => 0,
					'position'              => 'normal',
					'style'                 => 'default',
					'label_placement'       => 'top',
					'instruction_placement' => 'label',
					'hide_on_screen'        => '',
					'active'                => true,
					'description'           => '',
				)
			);

			// Dark Web Settings (for template dark-web-minute.php)
			acf_add_local_field_group(
				array(
					'key'                   => 'group_61f7eba9633c5',
					'title'                 => 'DarkWeb settings',
					'fields'                => array(
						array(
							'key'               => 'field_61f7f3f6a03eb',
							'label'             => 'Text after title',
							'name'              => 'text_after_title',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'tabs'              => 'all',
							'toolbar'           => 'basic',
							'media_upload'      => 0,
							'delay'             => 0,
						),
						array(
							'key'               => 'field_61f7ebbd60c0e',
							'label'             => 'Dark Web Items',
							'name'              => 'dark_web_items',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_61f7ee7060c0f',
									'label'             => 'Credit cards offered for sale',
									'name'              => 'credit_cards_offered_for_sale',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Credit cards offered for sale',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61f7ee8860c10',
									'label'             => 'Posts',
									'name'              => 'posts',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Posts',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61f7ef7b60c11',
									'label'             => 'Replies',
									'name'              => 'replies',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Replies',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61f7ef9a60c12',
									'label'             => 'Drug related discussions',
									'name'              => 'drug_related_discussions',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Drug related discussions',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61f7efda60c13',
									'label'             => 'Ref. to leaks & breaches',
									'name'              => 'ref_to_leaks_and_breaches',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Ref. to leaks & breaches',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61f7f1cb60c14',
									'label'             => 'Malicious chats on Telegram',
									'name'              => 'malicious_chats_on_telegram',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Malicious chats on Telegram',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61f7f23460c15',
									'label'             => 'CVEs',
									'name'              => 'cves',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'CVEs',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61f7f25460c16',
									'label'             => 'Suspicious IPs shared',
									'name'              => 'suspicious_ips_shared',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Suspicious IPs shared',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61f7f27e60c17',
									'label'             => 'Malware links shared',
									'name'              => 'malware_links_shared',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Malware links shared',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61f7f2b260c18',
									'label'             => 'Emails shared',
									'name'              => 'emails_shared',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Emails shared',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
					),
					'location'              => array(
						array(
							array(
								'param'    => 'page_template',
								'operator' => '==',
								'value'    => 'dark-web-minute.php',
							),
						),
					),
					'menu_order'            => 0,
					'position'              => 'normal',
					'style'                 => 'default',
					'label_placement'       => 'top',
					'instruction_placement' => 'label',
					'hide_on_screen'        => '',
					'active'                => true,
					'description'           => '',
				)
			);

			// Rgbcode Map Options
			acf_add_local_field_group(
				array(
					'key'                   => 'group_61e95f20e082f',
					'title'                 => 'Rgbcode Map Options',
					'fields'                => array(
						array(
							'key'               => 'field_61f8d31f730d5',
							'label'             => 'Header',
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_61f8d3e0730d8',
							'label'             => 'Text after logo',
							'name'              => 'text_after_logo',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Know what\'s out there',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61f8d383730d6',
							'label'             => 'Form',
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_61f8d39a730d7',
							'label'             => 'Form title',
							'name'              => 'form_title',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'GET YOUR FREE CUSTOMIZED REPORT',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61f8d39a730d9',
							'label'             => 'The text after sending the letter',
							'name'              => 'text_after_sending',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Done! The report will arrive in your inbox within 15 minutes',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61f8d39a730z9',
							'label'             => 'The email error text',
							'name'              => 'rgbcode_email_error',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'Email address must contains cybersixgill.com',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_61f8d33a730d9',
							'label'             => 'The domain error text',
							'name'              => 'rgbcode_domain_error',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '"Company domain" should be a valid domain',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_620211a67f3ea',
							'label'             => 'Terms',
							'name'              => 'form_term_link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						array(
							'key'               => 'field_61e95f49372d0',
							'label'             => 'Mail(Report) Settings',
							'name'              => 'mail_report_settings',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_61e95fcd372d1',
									'label'             => 'Your subject',
									'name'              => 'subject',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Report from CyberSixgill',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_61e9602c372d2',
									'label'             => 'Your Email to receive a copy of the report',
									'name'              => 'email_for_copy_report',
									'type'              => 'email',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
								),
								array(
									'key'               => 'field_61e960b7372d3',
									'label'             => 'Body text',
									'name'              => 'body_text',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Thank you for ordering the report!',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_61f8d383730d8',
							'label'             => 'Captcha',
							'name'              => '',
							'type'              => 'tab',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'placement'         => 'left',
							'endpoint'          => 0,
						),
						array(
							'key'               => 'field_6194f7a61f17c',
							'label'             => __( 'Captcha Site Key', 'rgbcode-map' ),
							'name'              => 'rgbcode_captcha_site_key',
							'type'              => 'text',
							'instructions'      => __( 'You can get the keys <a href="https://www.google.com/recaptcha/admin/create" target="_blank">here</a>', 'rgbcode-map' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_6194f7e41f17d',
							'label'             => __( 'Captcha Secret Key', 'rgbcode-map' ),
							'name'              => 'rgbcode_captcha_secret_key',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
					'location'              => array(
						array(
							array(
								'param'    => 'options_page',
								'operator' => '==',
								'value'    => 'rgbcode-map-options',
							),
						),
					),
					'menu_order'            => 0,
					'position'              => 'normal',
					'style'                 => 'default',
					'label_placement'       => 'top',
					'instruction_placement' => 'label',
					'hide_on_screen'        => '',
					'active'                => true,
					'description'           => '',
				)
			);
		}
	}
}
